In [18]:
import numpy as np
from twobessel import *
import matplotlib.pyplot as plt
import cambPK 

In [19]:
%run cambPK.py

In [20]:
cambPK.pk_out

array([[1.00000000e-04, 4.24842850e+02],
       [1.01037270e-04, 4.29092395e+02],
       [1.02085299e-04, 4.33384401e+02],
       ...,
       [2.93871892e+00, 5.23615280e+00],
       [2.96920137e+00, 5.10359479e+00],
       [3.00000000e+00, 4.97432191e+00]])

In [21]:
k, pk = np.loadtxt('Pkz0.0.dat', usecols=(0, 1), unpack=True)

# Get the logk-spacing
dlnk = np.log(k[1]/k[0])

N = k.size
print('Number of data points: '+str(N))

ell1 = 0
ell2 = 0
nu = 1.01

# Define the input 'kernel'. It has to be a matri: transform the pk to a diagonal matrix
pk1k2 = np.diag(k**3 * pk / dlnk)

Number of data points: 1000


In [22]:
# Define the class for spherical Bessel 

sph_bessel = two_sph_bessel(k, k, pk1k2, nu1=nu, nu2=nu,  N_extrap_low=0, N_extrap_high=0, c_window_width=0.25, N_pad=0)

r1, r2, Fr1Fr2 = sph_bessel.two_sph_bessel(ell1, ell2)

1000 1000
(1000, 1000)
1000 1000


In [38]:
# Drop results above 200 Mpc/h

criterion = r1 <= 200

d1 = r1[criterion]
d2 = r2[criterion]

var_00 = Fr1Fr2[:len(d1), :len(d2)]

In [39]:
np.shape(var_00)

(575, 575)

In [40]:
np.shape(Fr1Fr2)

(1000, 1000)

In [50]:
from scipy.interpolate import RectBivariateSpline

# Create an interpolation function
f = RectBivariateSpline(d1, d2, var_00)

# Now you can call f with new r1 and r2 values to get an interpolated Fr1r2 value
r1_new = 20.  # replace with your desired r1 value
r2_new = 20.  # replace with your desired r2 value
Fr1r2_new = f(r1_new, r2_new)

In [51]:
Fr1r2_new

array([[2.34205574]])

In [66]:
d1[325]

20.012497989690385

In [67]:
var_00[325, 325]

2.3397888351090406

In [70]:
d = np.arange(4, 175, 4)

d

array([  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
        56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100, 104,
       108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152, 156,
       160, 164, 168, 172])

In [71]:
var_00_172 = f(d, d)

In [72]:
np.shape(var_00_172)

(43, 43)